# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexis/Documents/Esgi/Projets/C/yamlDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexis/Documents/Esgi/Projets/C/yamlDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.5/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.9.5/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexis/Documents/Esgi/Projets/C/yamlDB/CMakeFiles /Users/alexis/Documents/Esgi/Projets/C/yamlDB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexis/Documents/Esgi/Projets/C/yamlDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yamlDB

# Build rule for target.
yamlDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yamlDB
.PHONY : yamlDB

# fast build rule for target.
yamlDB/fast:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/build
.PHONY : yamlDB/fast

sources/database/database.o: sources/database/database.c.o

.PHONY : sources/database/database.o

# target to build an object file
sources/database/database.c.o:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/database/database.c.o
.PHONY : sources/database/database.c.o

sources/database/database.i: sources/database/database.c.i

.PHONY : sources/database/database.i

# target to preprocess a source file
sources/database/database.c.i:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/database/database.c.i
.PHONY : sources/database/database.c.i

sources/database/database.s: sources/database/database.c.s

.PHONY : sources/database/database.s

# target to generate assembly for a file
sources/database/database.c.s:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/database/database.c.s
.PHONY : sources/database/database.c.s

sources/main.o: sources/main.c.o

.PHONY : sources/main.o

# target to build an object file
sources/main.c.o:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/main.c.o
.PHONY : sources/main.c.o

sources/main.i: sources/main.c.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.c.i:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/main.c.i
.PHONY : sources/main.c.i

sources/main.s: sources/main.c.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.c.s:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/main.c.s
.PHONY : sources/main.c.s

sources/table/table.o: sources/table/table.c.o

.PHONY : sources/table/table.o

# target to build an object file
sources/table/table.c.o:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/table/table.c.o
.PHONY : sources/table/table.c.o

sources/table/table.i: sources/table/table.c.i

.PHONY : sources/table/table.i

# target to preprocess a source file
sources/table/table.c.i:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/table/table.c.i
.PHONY : sources/table/table.c.i

sources/table/table.s: sources/table/table.c.s

.PHONY : sources/table/table.s

# target to generate assembly for a file
sources/table/table.c.s:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/table/table.c.s
.PHONY : sources/table/table.c.s

sources/utils/xmalloc.o: sources/utils/xmalloc.c.o

.PHONY : sources/utils/xmalloc.o

# target to build an object file
sources/utils/xmalloc.c.o:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/utils/xmalloc.c.o
.PHONY : sources/utils/xmalloc.c.o

sources/utils/xmalloc.i: sources/utils/xmalloc.c.i

.PHONY : sources/utils/xmalloc.i

# target to preprocess a source file
sources/utils/xmalloc.c.i:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/utils/xmalloc.c.i
.PHONY : sources/utils/xmalloc.c.i

sources/utils/xmalloc.s: sources/utils/xmalloc.c.s

.PHONY : sources/utils/xmalloc.s

# target to generate assembly for a file
sources/utils/xmalloc.c.s:
	$(MAKE) -f CMakeFiles/yamlDB.dir/build.make CMakeFiles/yamlDB.dir/sources/utils/xmalloc.c.s
.PHONY : sources/utils/xmalloc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... yamlDB"
	@echo "... sources/database/database.o"
	@echo "... sources/database/database.i"
	@echo "... sources/database/database.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/table/table.o"
	@echo "... sources/table/table.i"
	@echo "... sources/table/table.s"
	@echo "... sources/utils/xmalloc.o"
	@echo "... sources/utils/xmalloc.i"
	@echo "... sources/utils/xmalloc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

